---
spring:
  cloud:
    config:
      name: ifood-service-restaurant
      discovery:
        serviceId: ifood-service-config
        enabled: true
  datasource:
    url: jdbc:h2:mem:ifoodDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false