INSERT INTO RESTAURANT (RESTAURANT_ID, NAME) VALUES (1, 'LAPERO');
INSERT INTO RESTAURANT (RESTAURANT_ID, NAME) VALUES (2, 'LEJAZZ');
INSERT INTO RESTAURANT (RESTAURANT_ID, NAME) VALUES (3, 'TANUKI');