---
spring:
  application:
    name: ifood-service-discovery
server:
  port: 8010

eureka:
  instance:
    hostname: localhost 
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    registerWithEureka: false
    fetchRegistry: false 