---
spring:
     application:
          name: ifood-service-restaurant
     h2:
          console: 
               enabled: true
               path: /h2-console
     datasource:
          data: classpath:data.sql
          url: jdbc:h2:mem:ifoodDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          driver-class-name: org.h2.Driver
          username: sa
          password:
          name: ifoodDb
server:
  port: 8083
 
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
 
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create    